language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t dsmithhcm/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dsmithhcm/docker-react npm run test

# deploy:
  # provider: "elasticbeanstalk"
  # region: "us-east2"
  # app: "docker"
  # env: "Docker-env"
  # bucket_name: "insert-s3_bucket"
  # bucket_path: "docker"
  # access_key_id: "$access_key"
  # secret_access_key: "$secret_key"
  # on:
    # branch: origin